<?php

return [
    [
        'id' => 1,
        'name' => 'Unbekannt',
        'occupation' => null,
        'url' => null,
        'published' => 1,
        'created_at' => '2020-05-16 22:05:40',
        'updated_at' => '2020-05-16 22:06:34',
        'deleted_at' => null,
    ],
    [
        'id' => 2,
        'name' => 'Sybille Seuffer',
        'occupation' => null,
        'url' => null,
        'published' => 1,
        'created_at' => '2020-05-16 22:05:40',
        'updated_at' => '2020-05-16 22:06:34',
        'deleted_at' => null,
    ],
    [
        'id' => 3,
        'name' => 'Hermann Hesse',
        'occupation' => 'deutsch-schweizerischer Schriftsteller, Dichter und Maler',
        'url' => 'https://de.wikipedia.org/wiki/Hermann_Hesse',
        'published' => 1,
        'created_at' => '2020-05-16 22:07:32',
        'updated_at' => '2020-05-16 22:07:32',
        'deleted_at' => null,
    ],
    [
        'id' => 4,
        'name' => 'Jean Paul',
        'occupation' => 'deutscher Schriftsteller',
        'url' => 'https://de.wikipedia.org/wiki/Jean_Paul',
        'published' => 1,
        'created_at' => '2020-05-16 22:07:54',
        'updated_at' => '2020-05-16 22:07:54',
        'deleted_at' => null,
    ],
    [
        'id' => 5,
        'name' => 'Albert Einstein',
        'occupation' => 'deutsch-US-amerikanischer Physiker',
        'url' => 'https://de.wikipedia.org/wiki/Albert_Einstein',
        'published' => 1,
        'created_at' => '2020-05-16 22:08:12',
        'updated_at' => '2020-05-16 22:08:12',
        'deleted_at' => null,
    ],
    [
        'id' => 6,
        'name' => 'Aristoteles',
        'occupation' => 'griechischer Philosoph',
        'url' => 'https://de.wikipedia.org/wiki/Aristoteles',
        'published' => 1,
        'created_at' => '2020-05-16 22:08:24',
        'updated_at' => '2020-05-16 22:08:24',
        'deleted_at' => null,
    ],
    [
        'id' => 7,
        'name' => 'Christian August Vulpius',
        'occupation' => 'deutscher Schriftsteller',
        'url' => 'https://de.wikipedia.org/wiki/Christian_August_Vulpius',
        'published' => 1,
        'created_at' => '2020-05-16 22:08:34',
        'updated_at' => '2020-05-16 22:08:34',
        'deleted_at' => null,
    ],
    [
        'id' => 8,
        'name' => 'Buddha',
        'occupation' => 'Religionsstifter',
        'url' => 'https://de.wikipedia.org/wiki/Buddha#Etymologie',
        'published' => 1,
        'created_at' => '2021-01-06 23:49:20',
        'updated_at' => '2021-01-06 23:49:20',
        'deleted_at' => null,
    ],
];
