<?php

return [
    [
        'id' => 1,
        'slug' => 'speech:targets',
        'title' => 'Themenangebote',
        'caption' => null,
        'body' => "## Themenangebote f\xc3\xbcr\n\n* Frauenfr\xc3\xbchst\xc3\xbcckstreffen\n* Kindergartenelternabend\n* Erwachsenenbildung\n* Fortbildung f\xc3\xbcr Erzieherinnen:\n\t* Was macht ein gutes Team aus?\n\t* Elterngespr\xc3\xa4che - kompetent f\xc3\xbchren\n\t* Therapeutische Interventionen bei Kindern mit Problemverhalten\n* Inhaltliche Gestaltung mit einem ausgew\xc3\xa4hlten B\xc3\xbcchertisch zum jeweiligen Thema!",
        'created_at' => '2020-06-25 22:03:17',
        'updated_at' => '2020-06-26 05:01:54',
        'deleted_at' => null,
    ],
    [
        'id' => 2,
        'slug' => 'speech:topics',
        'title' => 'Vortragsthemen',
        'caption' => null,
        'body' => "### Vortragsthemen\n\n* Wenn Kinder trotzen\n* Kinder k\xc3\xb6nnen Krisen meistern\n* Positives Erziehungsprogramm in Theorie und Praxis\n* Mit Kindern wertsch\xc3\xa4tzend und konsequent leben\n* Keine Angst vor Krach und Streit\n* Kinder zur Selbst\xc3\xa4ndigkeit erziehen / selbst\xc3\xa4ndig werden lassen\n* Geschwisterkonstellationen / Geschwisterpositionen\n* Kinder brauchen Grenzen\n* Kinder altersentsprechend f\xc3\xb6rdern ausgerichtet am Orientierungsplan\n* Fit in der Schule und was Eltern dazu tun k\xc3\xb6nnen\n* Fit f\xc3\xbcr die Schule (Vorschulkinder)\n\n---\n\n* Lebenslust statt Midlifefrust\n* Leselust - B\xc3\xbccher vorgestellt von Sybille Seuffer\n* Nein sagen ohne Schuldgef\xc3\xbchle\n* Keine Angst vor Krach und Streit\n* \"Anleitung zum Gl\xc3\xbccklichsein\" - Was wir f\xc3\xbcr ein gutes und gesundes Lebensgef\xc3\xbchl erlernen k\xc3\xb6nnen",
        'created_at' => '2020-06-26 02:28:54',
        'updated_at' => '2020-06-26 05:08:54',
        'deleted_at' => null,
    ],
    [
        'id' => 3,
        'slug' => 'consulting',
        'title' => 'Beratung',
        'caption' => "**Seit 20 Jahren arbeite ich als selbst\xc3\xa4ndige Therapeutin** mit Erwachsenen, Jugendlichen und Kindern. Ich bilde mich st\xc3\xa4ndig weiter und nehme [Supervisionen](https://de.wikipedia.org/wiki/Supervision) in Anspruch.",
        'body' => "## Schwerpunkte\n\n* Systemische Familientherapie\n* Genogrammarbeit/Familienskulptur\n* Gespr\xc3\xa4chstherapie\n* Krisenintervention\n* Aufsuchende Familientherapie\n* Paartherapie\n* Begleiteter Umgang\n* Erziehungsberatung\n* Trennungsbegleitung/Beratung von Patchworkfamilien\n* Suchtproblematik bei Jugendlichen\n* Angstst\xc3\xb6rungen\n* Emotionale Stressreduzierung\n* Lernen lernen\n* Lernblockaden/Lerntraining\n* Psychosomatische St\xc3\xb6rungen bei Kindern\n* Fit f\xc3\xbcr die Schule (Vorschulkinder)\n* Elternkurse\n* P\xc3\xa4dagogische Rundbriefe\n* Gespr\xc3\xa4chsgruppen\n* Selbstbewusstseinstraining\n* Maltherapie (Erwachsene und Kinder)\n* Coaching\n* Telefonberatung +49 (0) 7453 3264",
        'created_at' => '2020-06-25 23:52:44',
        'updated_at' => '2020-06-26 05:01:16',
        'deleted_at' => null,
    ],
    [
        'id' => 4,
        'slug' => 'learning',
        'title' => "Wenn Du diese oder \xc3\xa4hnliche...",
        'caption' => 'Lernen kann so einfach sein.',
        'body' => "## Wenn Du diese oder \xc3\xa4hnliche Erfahrungen mit Schule oder dem Lernen machst, dann bist Du bei mir richtig\n\n* Hilfe bei mir bleibt alles nur im Kurzzeitged\xc3\xa4chtnis.\n* Ich wusste viel mehr und in der Klassenarbeit hatte ich einen Blackout.\n* Hausaufgaben, ich hasse sie! Ich werde m\xc3\xbcde, wenn ich nur dran denke.\n* Meine Konzentration l\xc3\xa4sst so schnell nach und meine Eltern nennen das Faulheit.",
        'created_at' => '2020-06-26 03:18:25',
        'updated_at' => '2020-06-26 05:01:29',
        'deleted_at' => null,
    ],
    [
        'id' => 5,
        'slug' => 'learning:goals',
        'title' => 'Wir gehen wie folgt vor',
        'caption' => null,
        'body' => "### Wir gehen wie folgt vor\n\n* Gemeinsam finden wir heraus, was Du f\xc3\xbcr ein Lerntyp bist.\n* Ich zeige Dir Strategien, wie das Gelernte im Langzeitged\xc3\xa4chtnis ankommt.\n* Und wie Du Hausaufgaben sinnvoll gliedern und lernen kannst.",
        'created_at' => '2020-06-26 03:19:04',
        'updated_at' => '2020-06-26 05:01:35',
        'deleted_at' => null,
    ],
    [
        'id' => 6,
        'slug' => 'learning:promises',
        'title' => 'Folgendes kann ich Dir versichern',
        'caption' => null,
        'body' => "#### Folgendes kann ich Dir versichern\n\n* Wenn Lernen zum Erfolg f\xc3\xbchrt, kann es richtig Spa\xc3\x9f machen. \xf0\x9f\x8e\x89\n* In nur f\xc3\xbcnf Stunden Lerntraining, kannst Du einiges erreichen.\n\n*Also \xe2\x80\x93 Kopf hoch und locker bleiben! Es gibt Hilfe!*",
        'created_at' => '2020-06-26 03:20:18',
        'updated_at' => '2020-09-11 04:41:51',
        'deleted_at' => null,
    ],
    [
        'id' => 7,
        'slug' => 'imprint',
        'title' => 'Impressum',
        'caption' => "Verantwortlich f\xc3\xbcr den Inhalt dieser Webseite",
        'body' => "Der Inhalt der Internetseiten wurde von vivien.ag sorgf\xc3\xa4ltig bearbeitet und gepr\xc3\xbcft. vivien.ag \xc3\xbcbernimmt jedoch keine Gew\xc3\xa4hr f\xc3\xbcr Richtigkeit, Vollst\xc3\xa4ndigkeit und Aktualit\xc3\xa4t der bereitgestellten Informationen. Sofern durch \"Links\" auf fremde Internetseiten verwiesen wird, ist vivien.ag f\xc3\xbcr den Inhalt der Seiten nicht verantwortlich. Wir behalten uns das Recht vor, Aktualisierungen und \xc3\x84nderungen an den bereitgestellten Informationen ohne vorherige Ank\xc3\xbcndigung zu ver\xc3\xa4ndern, zu erg\xc3\xa4nzen und zu l\xc3\xb6schen.",
        'created_at' => '2020-06-26 07:40:17',
        'updated_at' => '2022-01-13 00:07:34',
        'deleted_at' => null,
    ],
    [
        'id' => 8,
        'slug' => 'data-protection',
        'title' => "Datenschutzerkl\xc3\xa4rung",
        'caption' => null,
        'body' => "## Allgemeiner Hinweis und Pflichtinformationen\n\nDiese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. (\xe2\x80\x9eGoogle\xe2\x80\x9c). Google Analytics verwendet sog. \xe2\x80\x9eCookies\xe2\x80\x9c, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie erm\xc3\xb6glichen. Die durch den Cookie erzeugten Informationen \xc3\xbcber Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA \xc3\xbcbertragen und dort gespeichert. Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite, wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europ\xc3\xa4ischen Union oder in anderen Vertragsstaaten des Abkommens \xc3\xbcber den Europ\xc3\xa4ischen Wirtschaftsraum zuvor gek\xc3\xbcrzt.\n\nNur in Ausnahmef\xc3\xa4llen wird die volle IP-Adresse an einen Server von Google in den USA \xc3\xbcbertragen und dort gek\xc3\xbcrzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports \xc3\xbcber die Websiteaktivit\xc3\xa4ten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegen\xc3\xbcber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser \xc3\xbcbermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengef\xc3\xbchrt. Sie k\xc3\xb6nnen die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht s\xc3\xa4mtliche Funktionen dieser Website vollumf\xc3\xa4nglich werden nutzen k\xc3\xb6nnen.\n\nSie k\xc3\xb6nnen dar\xc3\xbcber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verf\xc3\xbcgbare Browser-Plugin herunterladen und installieren:\n\n[Browser Add On zur Deaktivierung von Google Analytics](http://tools.google.com/dlpage/gaoptout?hl=de).\n\n## Benennung der verantwortlichen Stelle\n\nDie verantwortliche Stelle f\xc3\xbcr die Datenverarbeitung auf dieser Website ist:\n\n**Sybille Seuffer**  \nGei\xc3\x9fwiesen 24/1  \n72227 Egenhausen\n\nDie verantwortliche Stelle entscheidet allein oder gemeinsam mit anderen \xc3\xbcber die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z.B. Namen, Kontaktdaten o.\xc3\x84.).\n\n## Widerruf Ihrer Einwilligung zur Datenverarbeitung\n\nNur mit Ihrer ausdr\xc3\xbccklichen Einwilligung sind einige Vorg\xc3\xa4nge der Datenverarbeitung m\xc3\xb6glich. Ein Widerruf Ihrer bereits erteilten Einwilligung ist jederzeit m\xc3\xb6glich. F\xc3\xbcr den Widerruf gen\xc3\xbcgt eine formlose Mitteilung per E-Mail. Die Rechtm\xc3\xa4\xc3\x9figkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unber\xc3\xbchrt.\n\n## Recht auf Beschwerde bei der zust\xc3\xa4ndigen Aufsichtsbeh\xc3\xb6rde\n\nAls Betroffener steht Ihnen im Falle eines datenschutzrechtlichen Versto\xc3\x9fes ein Beschwerderecht bei der zust\xc3\xa4ndigen Aufsichtsbeh\xc3\xb6rde zu. Zust\xc3\xa4ndige Aufsichtsbeh\xc3\xb6rde bez\xc3\xbcglich datenschutzrechtlicher Fragen ist der Landesdatenschutzbeauftragte des Bundeslandes, in dem sich der Sitz unseres Unternehmens befindet. Der folgende Link stellt eine Liste der Datenschutzbeauftragten sowie deren Kontaktdaten bereit: [https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html](https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html).\n\n## Recht auf Daten\xc3\xbcbertragbarkeit\n\nIhnen steht das Recht zu, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erf\xc3\xbcllung eines Vertrags automatisiert verarbeiten, an sich oder an Dritte aush\xc3\xa4ndigen zu lassen. Die Bereitstellung erfolgt in einem maschinenlesbaren Format. Sofern Sie die direkte \xc3\x9cbertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.\n\n## Recht auf Auskunft, Berichtigung, Sperrung, L\xc3\xb6schung\n\nSie haben jederzeit im Rahmen der geltenden gesetzlichen Bestimmungen das Recht auf unentgeltliche Auskunft \xc3\xbcber Ihre gespeicherten personenbezogenen Daten, Herkunft der Daten, deren Empf\xc3\xa4nger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung, Sperrung oder L\xc3\xb6schung dieser Daten. Diesbez\xc3\xbcglich und auch zu weiteren Fragen zum Thema personenbezogene Daten k\xc3\xb6nnen Sie sich jederzeit \xc3\xbcber die im Impressum aufgef\xc3\xbchrten Kontaktm\xc3\xb6glichkeiten an uns wenden.\n\n## SSL- bzw. TLS-Verschl\xc3\xbcsselung\n\nAus Sicherheitsgr\xc3\xbcnden und zum Schutz der \xc3\x9cbertragung vertraulicher Inhalte, die Sie an uns als Seitenbetreiber senden, nutzt unsere Website eine SSL-bzw. TLS-Verschl\xc3\xbcsselung. Damit sind Daten, die Sie \xc3\xbcber diese Website \xc3\xbcbermitteln, f\xc3\xbcr Dritte nicht mitlesbar. Sie erkennen eine verschl\xc3\xbcsselte Verbindung an der \xe2\x80\x9ehttps://\xe2\x80\x9c Adresszeile Ihres Browsers und am Schloss-Symbol in der Browserzeile.\n\n## Server-Log-Dateien\n\nIn Server-Log-Dateien erhebt und speichert der Provider der Website automatisch Informationen, die Ihr Browser automatisch an uns \xc3\xbcbermittelt. Dies sind:\n\n- Besuchte Seite auf unserer Domain\n- Datum und Uhrzeit der Serveranfrage\n- Browsertyp und Browserversion\n- Verwendetes Betriebssystem\n- Referrer URL\n- Hostname des zugreifenden Rechners\n- IP-Adresse\n\nEs findet keine Zusammenf\xc3\xbchrung dieser Daten mit anderen Datenquellen statt. Grundlage der Datenverarbeitung bildet Art. 6 Abs. 1 lit. b DSGVO, der die Verarbeitung von Daten zur Erf\xc3\xbcllung eines Vertrags oder vorvertraglicher Ma\xc3\x9fnahmen gestattet.\n\n## Registrierung auf dieser Website\n\nZur Nutzung bestimmter Funktionen k\xc3\xb6nnen Sie sich auf unserer Website registrieren. Die \xc3\xbcbermittelten Daten dienen ausschlie\xc3\x9flich zum Zwecke der Nutzung des jeweiligen Angebotes oder Dienstes. Bei der Registrierung abgefragte Pflichtangaben sind vollst\xc3\xa4ndig anzugeben. Andernfalls werden wir die Registrierung ablehnen.\n\nIm Falle wichtiger \xc3\x84nderungen, etwa aus technischen Gr\xc3\xbcnden, informieren wir Sie per E-Mail. Die E-Mail wird an die Adresse versendet, die bei der Registrierung angegeben wurde.\n\nDie Verarbeitung der bei der Registrierung eingegebenen Daten erfolgt auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Ein Widerruf Ihrer bereits erteilten Einwilligung ist jederzeit m\xc3\xb6glich. F\xc3\xbcr den Widerruf gen\xc3\xbcgt eine formlose Mitteilung per E-Mail. Die Rechtm\xc3\xa4\xc3\x9figkeit der bereits erfolgten Datenverarbeitung bleibt vom Widerruf unber\xc3\xbchrt.\n\nWir speichern die bei der Registrierung erfassten Daten w\xc3\xa4hrend des Zeitraums, den Sie auf unserer Website registriert sind. Ihren Daten werden gel\xc3\xb6scht, sollten Sie Ihre Registrierung aufheben. Gesetzliche Aufbewahrungsfristen bleiben unber\xc3\xbchrt.\n\n## Kontaktformular\n\nPer Kontaktformular \xc3\xbcbermittelte Daten werden einschlie\xc3\x9flich Ihrer Kontaktdaten gespeichert, um Ihre Anfrage bearbeiten zu k\xc3\xb6nnen oder um f\xc3\xbcr Anschlussfragen bereitzustehen. Eine Weitergabe dieser Daten findet ohne Ihre Einwilligung nicht statt.\n\nDie Verarbeitung der in das Kontaktformular eingegebenen Daten erfolgt ausschlie\xc3\x9flich auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Ein Widerruf Ihrer bereits erteilten Einwilligung ist jederzeit m\xc3\xb6glich. F\xc3\xbcr den Widerruf gen\xc3\xbcgt eine formlose Mitteilung per E-Mail. Die Rechtm\xc3\xa4\xc3\x9figkeit der bis zum Widerruf erfolgten Datenverarbeitungsvorg\xc3\xa4nge bleibt vom Widerruf unber\xc3\xbchrt.\n\n\xc3\x9cber das Kontaktformular \xc3\xbcbermittelte Daten verbleiben bei uns, bis Sie uns zur L\xc3\xb6schung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder keine Notwendigkeit der Datenspeicherung mehr besteht. Zwingende gesetzliche Bestimmungen - insbesondere Aufbewahrungsfristen - bleiben unber\xc3\xbchrt.\n\n## Speicherdauer von Beitr\xc3\xa4gen und Kommentaren\n\nBeitr\xc3\xa4ge und Kommentare sowie damit in Verbindung stehende Daten, wie beispielsweise IP-Adressen, werden gespeichert. Der Inhalt verbleibt auf unserer Website, bis er vollst\xc3\xa4ndig gel\xc3\xb6scht wurde oder aus rechtlichen Gr\xc3\xbcnden gel\xc3\xb6scht werden musste.\n\nDie Speicherung der Beitr\xc3\xa4ge und Kommentare erfolgt auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Ein Widerruf Ihrer bereits erteilten Einwilligung ist jederzeit m\xc3\xb6glich. F\xc3\xbcr den Widerruf gen\xc3\xbcgt eine formlose Mitteilung per E-Mail. Die Rechtm\xc3\xa4\xc3\x9figkeit bereits erfolgter Datenverarbeitungsvorg\xc3\xa4nge bleibt vom Widerruf unber\xc3\xbchrt.\n\n## Abonnieren von Kommentaren\n\nSie k\xc3\xb6nnen als Nutzer unserer Website nach erfolgter Anmeldung Kommentare abonnieren. Mit einer Best\xc3\xa4tigungs-E-Mail pr\xc3\xbcfen wir, ob Sie der Inhaber der angegebenen E-Mail-Adresse sind. Sie k\xc3\xb6nnen die Abo-Funktion f\xc3\xbcr Kommentare jederzeit \xc3\xbcber einen Link, der sich in einer Abo-Mail befindet, abbestellen. Zur Einrichtung des Abonnements eingegebene Daten werden im Falle der Abmeldung gel\xc3\xb6scht. Sollten diese Daten f\xc3\xbcr andere Zwecke und an anderer Stelle an uns \xc3\xbcbermittelt worden sein, verbleiben diese weiterhin bei uns.\n\n## Newsletter-Daten\n\nZum Versenden unseres Newsletters ben\xc3\xb6tigen wir von Ihnen eine E-Mail-Adresse. Eine Verifizierung der angegebenen E-Mail-Adresse ist notwendig und der Empfang des Newsletters ist einzuwilligen. Erg\xc3\xa4nzende Daten werden nicht erhoben oder sind freiwillig. Die Verwendung der Daten erfolgt ausschlie\xc3\x9flich f\xc3\xbcr den Versand des Newsletters.\n\nDie bei der Newsletteranmeldung gemachten Daten werden ausschlie\xc3\x9flich auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) verarbeitet. Ein Widerruf Ihrer bereits erteilten Einwilligung ist jederzeit m\xc3\xb6glich. F\xc3\xbcr den Widerruf gen\xc3\xbcgt eine formlose Mitteilung per E-Mail oder Sie melden sich \xc3\xbcber den \"Austragen\"-Link im Newsletter ab. Die Rechtm\xc3\xa4\xc3\x9figkeit der bereits erfolgten Datenverarbeitungsvorg\xc3\xa4nge bleibt vom Widerruf unber\xc3\xbchrt.\n\nZur Einrichtung des Abonnements eingegebene Daten werden im Falle der Abmeldung gel\xc3\xb6scht. Sollten diese Daten f\xc3\xbcr andere Zwecke und an anderer Stelle an uns \xc3\xbcbermittelt worden sein, verbleiben diese weiterhin bei uns.\n\n## Cookies\n\nUnsere Website verwendet Cookies. Das sind kleine Textdateien, die Ihr Webbrowser auf Ihrem Endger\xc3\xa4t speichert. Cookies helfen uns dabei, unser Angebot nutzerfreundlicher, effektiver und sicherer zu machen.\n\nEinige Cookies sind \xe2\x80\x9cSession-Cookies.\xe2\x80\x9d Solche Cookies werden nach Ende Ihrer Browser-Sitzung von selbst gel\xc3\xb6scht. Hingegen bleiben andere Cookies auf Ihrem Endger\xc3\xa4t bestehen, bis Sie diese selbst l\xc3\xb6schen. Solche Cookies helfen uns, Sie bei R\xc3\xbcckkehr auf unserer Website wiederzuerkennen.\n\nMit einem modernen Webbrowser k\xc3\xb6nnen Sie das Setzen von Cookies \xc3\xbcberwachen, einschr\xc3\xa4nken oder unterbinden. Viele Webbrowser lassen sich so konfigurieren, dass Cookies mit dem Schlie\xc3\x9fen des Programms von selbst gel\xc3\xb6scht werden. Die Deaktivierung von Cookies kann eine eingeschr\xc3\xa4nkte Funktionalit\xc3\xa4t unserer Website zur Folge haben.\n\nDas Setzen von Cookies, die zur Aus\xc3\xbcbung elektronischer Kommunikationsvorg\xc3\xa4nge oder der Bereitstellung bestimmter, von Ihnen erw\xc3\xbcnschter Funktionen (z.B. Warenkorb) notwendig sind, erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Als Betreiber dieser Website haben wir ein berechtigtes Interesse an der Speicherung von Cookies zur technisch fehlerfreien und reibungslosen Bereitstellung unserer Dienste. Sofern die Setzung anderer Cookies (z.B. f\xc3\xbcr Analyse-Funktionen) erfolgt, werden diese in dieser Datenschutzerkl\xc3\xa4rung separat behandelt.\n\n## Google Analytics\n\nUnsere Website verwendet Funktionen des Webanalysedienstes Google Analytics. Anbieter des Webanalysedienstes ist die Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.\n\nGoogle Analytics verwendet \"Cookies.\" Das sind kleine Textdateien, die Ihr Webbrowser auf Ihrem Endger\xc3\xa4t speichert und eine Analyse der Website-Benutzung erm\xc3\xb6glichen. Mittels Cookie erzeugte Informationen \xc3\xbcber Ihre Benutzung unserer Website werden an einen Server von Google \xc3\xbcbermittelt und dort gespeichert. Server-Standort ist im Regelfall die USA.\n\nDas Setzen von Google-Analytics-Cookies erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Als Betreiber dieser Website haben wir  ein berechtigtes Interesse an der Analyse des Nutzerverhaltens, um unser Webangebot und ggf. auch Werbung zu optimieren.\n\n#### IP-Anonymisierung\n\nWir setzen Google Analytics in Verbindung mit der Funktion IP-Anonymisierung ein. Sie gew\xc3\xa4hrleistet, dass Google Ihre IP-Adresse innerhalb von Mitgliedstaaten der Europ\xc3\xa4ischen Union oder in anderen Vertragsstaaten des Abkommens \xc3\xbcber den Europ\xc3\xa4ischen Wirtschaftsraum vor der \xc3\x9cbermittlung in die USA k\xc3\xbcrzt. Es kann Ausnahmef\xc3\xa4lle geben, in denen Google die volle IP-Adresse an einen Server in den USA \xc3\xbcbertr\xc3\xa4gt und dort k\xc3\xbcrzt. In unserem Auftrag wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports \xc3\xbcber Websiteaktivit\xc3\xa4ten zu erstellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegen\xc3\xbcber uns zu erbringen. Es findet keine Zusammenf\xc3\xbchrung der von Google Analytics \xc3\xbcbermittelten IP-Adresse mit anderen Daten von Google statt.\n\n#### Browser Plugin\n\nDas Setzen von Cookies durch Ihren Webbrowser ist verhinderbar. Einige Funktionen unserer Website k\xc3\xb6nnten dadurch jedoch eingeschr\xc3\xa4nkt werden. Ebenso k\xc3\xb6nnen Sie die Erfassung von Daten bez\xc3\xbcglich Ihrer Website-Nutzung einschlie\xc3\x9flich Ihrer IP-Adresse mitsamt anschlie\xc3\x9fender Verarbeitung durch Google unterbinden. Dies ist m\xc3\xb6glich, indem Sie das \xc3\xbcber folgenden Link erreichbare Browser-Plugin herunterladen und installieren: [https://tools.google.com/dlpage/gaoptout?hl=de](https://tools.google.com/dlpage/gaoptout?hl=de).\n\n#### Widerspruch gegen die Datenerfassung\n\nSie k\xc3\xb6nnen die Erfassung Ihrer Daten durch Google Analytics verhindern, indem Sie auf folgenden Link klicken. Es wird ein Opt-Out-Cookie gesetzt, der die Erfassung Ihrer Daten bei zuk\xc3\xbcnftigen Besuchen unserer Website verhindert: Google Analytics deaktivieren.\n\nEinzelheiten zum Umgang mit Nutzerdaten bei Google Analytics finden Sie in der Datenschutzerkl\xc3\xa4rung von Google: [https://support.google.com/analytics/answer/6004245?hl=de](https://support.google.com/analytics/answer/6004245?hl=de).\n\n#### Auftragsverarbeitung\n\nZur vollst\xc3\xa4ndigen Erf\xc3\xbcllung der gesetzlichen Datenschutzvorgaben haben wir mit Google einen Vertrag \xc3\xbcber die Auftragsverarbeitung abgeschlossen.\n\n#### Demografische Merkmale bei Google Analytics\n\nUnsere Website verwendet die Funktion \xe2\x80\x9cdemografische Merkmale\xe2\x80\x9d von Google Analytics. Mit ihr lassen sich Berichte erstellen, die Aussagen zu Alter, Geschlecht und Interessen der Seitenbesucher enthalten. Diese Daten stammen aus interessenbezogener Werbung von Google sowie aus Besucherdaten von Drittanbietern. Eine Zuordnung der Daten zu einer bestimmten Person ist nicht m\xc3\xb6glich. Sie k\xc3\xb6nnen diese Funktion jederzeit deaktivieren. Dies ist \xc3\xbcber die Anzeigeneinstellungen in Ihrem Google-Konto m\xc3\xb6glich oder indem Sie die Erfassung Ihrer Daten durch Google Analytics, wie im Punkt \xe2\x80\x9cWiderspruch gegen die Datenerfassung\xe2\x80\x9d erl\xc3\xa4utert, generell untersagen.\n\n## Google Web Fonts\n\nUnsere Website verwendet Web Fonts von Google. Anbieter ist die Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.\n\nDurch den Einsatz dieser Web Fonts wird es m\xc3\xb6glich Ihnen die von uns gew\xc3\xbcnschte Darstellung unserer Website zu pr\xc3\xa4sentieren, unabh\xc3\xa4ngig davon welche Schriften Ihnen lokal zur Verf\xc3\xbcgung stehen. Dies erfolgt \xc3\xbcber den Abruf der Google Web Fonts von einem Server von Google in den USA und der damit verbundenen Weitergabe Ihre Daten an Google. Dabei handelt es sich um Ihre IP-Adresse und welche Seite Sie bei uns besucht haben. Der Einsatz von Google Web Fonts erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Als Betreiber dieser Website haben wir ein berechtigtes Interesse an der optimalen Darstellung und \xc3\x9cbertragung unseres Webauftritts.\n\nDas Unternehmen Google ist f\xc3\xbcr das us-europ\xc3\xa4ische Datenschutz\xc3\xbcbereinkommen \"Privacy Shield\" zertifiziert. Dieses Datenschutz\xc3\xbcbereinkommen soll die Einhaltung des in der EU geltenden Datenschutzniveaus gew\xc3\xa4hrleisten.\n\nEinzelheiten \xc3\xbcber Google Web Fonts finden Sie unter: [https://www.google.com/fonts#AboutPlace:about](https://www.google.com/fonts#AboutPlace:about) und weitere Informationen in den Datenschutzbestimmungen von Google: [https://policies.google.com/privacy/partners?hl=de](https://policies.google.com/privacy/partners?hl=de)",
        'created_at' => '2020-06-26 07:41:15',
        'updated_at' => '2020-06-27 02:02:02',
        'deleted_at' => null,
    ],
    [
        'id' => 9,
        'slug' => 'portrait',
        'title' => "\xc3\x9cber mich",
        'caption' => null,
        'body' => "{highlight}Ich liebe{/highlight}  \r\nKinder, italienisches Essen, Radfahren, Kunstausstellungen\r\n\r\n{highlight}Reiseziele{/highlight}  \r\nIrland, Madeira, USA\r\n\r\n{highlight}Hobbies{/highlight}  \r\nMalen, Lesen, Schreiben, Tanzen, St\xc3\xa4dtereisen\r\n\r\n{highlight}Lieblingstier{/highlight}  \r\nEule\r\n\r\n{highlight}Lieblingsfilm{/highlight}  \r\nGr\xc3\xbcne Tomaten, S\xc3\xa4ulen der Erde\r\n\r\n{highlight}Meine St\xc3\xa4rke{/highlight}  \r\nGeduld\r\n\r\n{highlight}Meine Schw\xc3\xa4che{/highlight}  \r\nNachteule\r\n\r\n{highlight}Motto ({year}){/highlight}  \r\nDie Ruhe selbst sein",
        'created_at' => '2020-06-27 02:03:43',
        'updated_at' => '2022-01-18 04:49:43',
        'deleted_at' => null,
    ],
    [
        'id' => 10,
        'slug' => 'portrait:services',
        'title' => 'Leistungen',
        'caption' => null,
        'body' => "* Frauengruppen\r\n* Paargruppen\r\n* Seminare\r\n* Vortr\xc3\xa4ge\r\n* Erziehungsberatung (PEP4Kids)\r\n* Einzelberatung / Paarberatung\r\n* Gespr\xc3\xa4chstherapie\r\n* Kreatives Schreiben\r\n* Malwerkstatt\r\n* Lerntraining\r\n* Telefonberatung",
        'created_at' => '2020-06-27 02:44:43',
        'updated_at' => '2020-07-08 17:41:04',
        'deleted_at' => null,
    ],
    [
        'id' => 11,
        'slug' => 'welcome:updates',
        'title' => 'Updates',
        'caption' => null,
        'body' => "### Seminare {year-last}/{year}\r\n**06.01.2021** / erstellt von [Sybille Seuffer](https://vivien.ag/portrait)\r\n\r\n#### Liebe Besucher, die [Termine/Seminare](https://vivien.ag/seminare) f\xc3\xbcr {year} sind nun online.\r\n\r\n**Herzliche Gr\xc3\xbc\xc3\x9fe**",
        'created_at' => '2020-06-28 01:11:57',
        'updated_at' => '2022-01-18 04:49:24',
        'deleted_at' => null,
    ],
    [
        'id' => 12,
        'slug' => 'welcome:no-events',
        'title' => 'Events',
        'caption' => '...',
        'body' => "**Leider k\xc3\xb6nnen aktuell aufgrund der Corona-Verordnung keine Seminare stattfinden.** &nbsp;\xf0\x9f\x98\xb7 \xf0\x9f\x98\x92\n\n\nGerne berate ich dich in der Zwischenzeit telefonisch: <span class=\"whitespace-no-wrap\">**+49 (0)7453 3264**</span>\n\n\n<small>Ich hoffe wir sehen uns bald wieder. Bleib gesund und steck den Kopf nicht in den Sand.</small>",
        'created_at' => '2020-12-09 20:48:52',
        'updated_at' => '2020-12-09 22:53:51',
        'deleted_at' => null,
    ],
    [
        'id' => 13,
        'slug' => 'contact',
        'title' => 'Kontakt',
        'caption' => null,
        'body' => "## Sybille Seuffer\nGei\xc3\x9fwiesen 24/1  \nD-72227 Egenhausen  \nTelefon {highlight}[+49 (0)7453 3264](tel:004974533264){/highlight}  \nE-Mail {highlight}[me@vivien.ag](mailto:me@vivien.ag){/highlight}  \noder via {highlight}[**Facebook**](https://www.facebook.com/sybille.seuffer){/highlight}",
        'created_at' => '2020-06-28 01:32:31',
        'updated_at' => '2020-06-29 08:39:19',
        'deleted_at' => null,
    ],
    [
        'id' => 14,
        'slug' => 'portrait:links',
        'title' => "Vortr\xc3\xa4ge und Seminare",
        'caption' => null,
        'body' => "Hier erf\xc3\xa4hrst du mehr \xc3\xbcber die von mir angebotenen  \n* [**Vortragsthemen**](/vortraege)\n* [**Beratungsschwerpunkte**](/beratung)\n* [**Lernstrategien**](/lerntraining)\n* und [**Seminare**](/seminare)",
        'created_at' => '2020-06-29 06:19:38',
        'updated_at' => '2020-06-29 06:23:45',
        'deleted_at' => null,
    ],
    [
        'id' => 18,
        'slug' => 'portrait:contact',
        'title' => 'Kontakt',
        'caption' => null,
        'body' => "**Telefon** {highlight}[+49 (0)7453 3264](tel:004974533264){/highlight}  \n**E-Mail** {highlight}[me@vivien.ag](mailto:me@vivien.ag){/highlight}  \noder via {highlight}[**Facebook**](https://www.facebook.com/sybille.seuffer){/highlight}\n\n<p class=\"mt-2 text-gray-500 text-sm\">  \nGei\xc3\x9fwiesen 24/1  \nD-72227 Egenhausen  \n</p>",
        'created_at' => '2020-06-29 06:29:29',
        'updated_at' => '2020-06-29 06:43:47',
        'deleted_at' => null,
    ],
];
