<?php

return [
    [
        'id' => 1,
        'content_view_id' => 3,
        'content_block_id' => 15,
        'slug' => 'welcome:updates',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 2,
        'content_view_id' => 3,
        'content_block_id' => 14,
        'slug' => 'welcome:no-events',
        'published' => 0,
        'order_column' => 2,
    ],
    [
        'id' => 3,
        'content_view_id' => 10,
        'content_block_id' => 16,
        'slug' => 'cookie-policy',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 4,
        'content_view_id' => 9,
        'content_block_id' => 3,
        'slug' => 'privacy-policy',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 5,
        'content_view_id' => 8,
        'content_block_id' => 4,
        'slug' => 'imprint',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 6,
        'content_view_id' => 7,
        'content_block_id' => 2,
        'slug' => 'contact',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 7,
        'content_view_id' => 6,
        'content_block_id' => 5,
        'slug' => 'learning',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 8,
        'content_view_id' => 11,
        'content_block_id' => 9,
        'slug' => 'portrait:contact',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 9,
        'content_view_id' => 11,
        'content_block_id' => 8,
        'slug' => 'portrait:about',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 10,
        'content_view_id' => 11,
        'content_block_id' => 11,
        'slug' => 'portrait:services',
        'published' => 1,
        'order_column' => 3,
    ],
    [
        'id' => 11,
        'content_view_id' => 11,
        'content_block_id' => 10,
        'slug' => 'portrait:links',
        'published' => 1,
        'order_column' => 4,
    ],
    [
        'id' => 12,
        'content_view_id' => 4,
        'content_block_id' => 12,
        'slug' => 'speeches:target-groups',
        'published' => 1,
        'order_column' => 1,
    ],
    [
        'id' => 13,
        'content_view_id' => 4,
        'content_block_id' => 13,
        'slug' => 'speeches:topics',
        'published' => 1,
        'order_column' => 2,
    ],
];
