<?php

return [
    [
        'id' => 1,
        'cookie_consent_provider_id' => 1,
        'cookie_name' => '*_cookie_consent',
        'cookie_purpose' => "<span class=\"font-medium\">Enth\xc3\xa4lt:</span>\n\n<ul class=\"list-disc ml-6 mt-4\">\n  <li class=\"py-1 text-xs\">\n\tdeine Cookie-Einstellungen\n  </li>\n  <li class=\"py-1 text-xs\">\n\tdie Information ob der Cookie-Banner bereits angezeigt wurde\n  </li>\n</ul>",
        'cookie_category' => 'Notwendig',
        'cookie_type' => 'HTTP',
        'cookie_lifetime' => 730,
        'encrypted' => 0,
        'required' => 1,
        'created_at' => '2020-06-21 13:37:57',
        'updated_at' => '2020-06-21 13:55:16',
    ],
    [
        'id' => 2,
        'cookie_consent_provider_id' => 1,
        'cookie_name' => '*_session',
        'cookie_purpose' => "<span class=\"font-medium\">Enth\xc3\xa4lt verschl\xc3\xbcsselte Sitzungsdaten:</span>\n\n<ul class=\"list-disc ml-6 mt-4\">\n  <li class=\"py-1\">\n\t<span class=\"font-medium\">_token</span>\n\t<br>\n\t<span class=\"text-xs\">XSRF-TOKEN (siehe unten)</span>\n  </li>\n  <li class=\"py-1\">\n\t<span class=\"font-medium\">_previous</span>\n\t<br>\n\t<span class=\"text-xs\">Zuletzte aufgerufene URL.</span>\n  </li>\n  <li class=\"py-1\">\n\t<span class=\"font-medium\">_flash</span>\n\t<br>\n\t<span class=\"text-xs\">Zur \xc3\x9cbergabe von Seiten\xc3\xbcbergreifenden Daten, wie z.B. der Fehlermeldungen nach dem Absenden eines Formulares oder der Erfolgsnachricht.</span>\n  </li>\n</ul",
        'cookie_category' => 'Notwendig',
        'cookie_type' => 'HTTP',
        'cookie_lifetime' => 365,
        'encrypted' => 1,
        'required' => 1,
        'created_at' => '2020-06-21 07:42:08',
        'updated_at' => '2020-06-21 13:55:21',
    ],
    [
        'id' => 3,
        'cookie_consent_provider_id' => 1,
        'cookie_name' => 'XSRF-TOKEN',
        'cookie_purpose' => "Sicherheitsma\xc3\x9fnahme gegen Cross-SiteService-Request-Forgery (CSRF oder XSRF abgek\xc3\xbcrzt), deutsch etwa Website-\xc3\xbcbergreifende Anfragenf\xc3\xa4lschung.\n<br>\n<br>\nAnhand des XSRF-Token wird sichergestellt, dass von dir \xc3\xbcbermittelten Daten auf ihrem Weg, zwischen Host (dein Ger\xc3\xa4t) und Server (meine Webseite), nicht von einem Hacker manipuliert werden.",
        'cookie_category' => 'Notwendig',
        'cookie_type' => 'HTTP',
        'cookie_lifetime' => 0,
        'encrypted' => 1,
        'required' => 1,
        'created_at' => '2020-06-21 07:51:29',
        'updated_at' => '2020-06-21 07:57:13',
    ],
    [
        'id' => 4,
        'cookie_consent_provider_id' => 2,
        'cookie_name' => '_gid',
        'cookie_purpose' => 'Registriert eine eindeutige ID, die verwendet wird, um statistische Daten dazu, wie der Besucher die Website nutzt, zu generieren.',
        'cookie_category' => 'Statistiken',
        'cookie_type' => 'HTTP',
        'cookie_lifetime' => 1,
        'encrypted' => 0,
        'required' => 0,
        'created_at' => '2020-06-21 14:04:13',
        'updated_at' => '2020-06-21 14:04:13',
    ],
    [
        'id' => 5,
        'cookie_consent_provider_id' => 2,
        'cookie_name' => '_gat',
        'cookie_purpose' => "Wird von Google Analytics verwendet, um die Anforderungsrate einzuschr\xc3\xa4nken.",
        'cookie_category' => 'Statistiken',
        'cookie_type' => 'HTTP',
        'cookie_lifetime' => 1,
        'encrypted' => 0,
        'required' => 0,
        'created_at' => '2020-06-21 14:05:30',
        'updated_at' => '2020-06-21 14:05:30',
    ],
    [
        'id' => 6,
        'cookie_consent_provider_id' => 2,
        'cookie_name' => '_ga',
        'cookie_purpose' => 'Registriert eine eindeutige ID, die verwendet wird, um statistische Daten dazu, wie der Besucher die Website nutzt, zu generieren.',
        'cookie_category' => 'Statistiken',
        'cookie_type' => 'HTTP',
        'cookie_lifetime' => 730,
        'encrypted' => 0,
        'required' => 0,
        'created_at' => '2020-06-21 14:06:22',
        'updated_at' => '2020-06-21 14:06:22',
    ],
];
