<?php

return [
    [
        'id' => 1,
        'name' => 'Egenhausen, Geisswiesen 24/1',
        'address' => 'Geisswiesen 24/1, 72227 Egenhausen',
        'description' => null,
        'url' => 'https://goo.gl/maps/5SYy3qiHmQvRcci4A',
        'created_at' => '2020-05-26 04:35:05',
        'updated_at' => '2020-05-26 04:37:17',
        'deleted_at' => null,
    ],
    [
        'id' => 2,
        'name' => "W\xc3\xb6rnersberger Anker",
        'address' => "W\xc3\xb6rnersberger Anker, Hauptstra\xc3\x9fe 32, 72299 W\xc3\xb6rnersberg",
        'description' => null,
        'url' => 'https://goo.gl/maps/rfXYiwRyqEshUG1f6',
        'created_at' => '2020-05-26 04:36:53',
        'updated_at' => '2020-05-26 04:36:53',
        'deleted_at' => null,
    ],
    [
        'id' => 3,
        'name' => "Atelier, Gr\xc3\xb6mbach",
        'address' => "Altensteiger Str. 43, 72294 Gr\xc3\xb6mbach",
        'description' => null,
        'url' => 'https://goo.gl/maps/GQBhEMvpb7sHtHdc7',
        'created_at' => '2020-05-26 04:38:06',
        'updated_at' => '2020-05-26 04:38:06',
        'deleted_at' => null,
    ],
    [
        'id' => 4,
        'name' => 'At home',
        'address' => null,
        'description' => "Im gem\xc3\xbctlichen Eigenheim",
        'url' => null,
        'created_at' => '2020-05-26 04:41:10',
        'updated_at' => '2020-10-14 03:50:32',
        'deleted_at' => null,
    ],
    [
        'id' => 5,
        'name' => 'Auf Nebenstrecken',
        'address' => null,
        'description' => 'Mit dem E-Bike auf Nebenstrecken',
        'url' => null,
        'created_at' => '2020-05-26 04:42:43',
        'updated_at' => '2020-10-14 03:50:36',
        'deleted_at' => null,
    ],
    [
        'id' => 6,
        'name' => 'Am Telefon',
        'address' => null,
        'description' => null,
        'url' => null,
        'created_at' => '2020-06-28 22:08:33',
        'updated_at' => '2020-10-14 03:50:26',
        'deleted_at' => null,
    ],
    [
        'id' => 7,
        'name' => 'Oberammergau',
        'address' => null,
        'description' => "Reisen mit Frauen! Sei dabei und f\xc3\xbchl dich frei!\n Du wirst kreativ, erweiterst deinen Horizont, erlebst eine unbeschwerte Zeit, lernst dich selbst besser kennen und sp\xc3\xbcrst, dass dadurch dein Leben reicher wird!",
        'url' => null,
        'created_at' => '2020-10-13 08:30:28',
        'updated_at' => '2020-10-14 03:50:40',
        'deleted_at' => null,
    ],
    [
        'id' => 8,
        'name' => 'Bodensee',
        'address' => null,
        'description' => null,
        'url' => null,
        'created_at' => '2020-10-14 03:51:24',
        'updated_at' => '2020-10-14 03:51:24',
        'deleted_at' => null,
    ],
    [
        'id' => 9,
        'name' => 'Heidelberg',
        'address' => null,
        'description' => null,
        'url' => null,
        'created_at' => '2020-10-14 03:51:42',
        'updated_at' => '2020-10-14 03:55:17',
        'deleted_at' => null,
    ],
    [
        'id' => 10,
        'name' => 'Schreibreise',
        'address' => 'Berlin',
        'description' => "Berlin weil es Berlin ist.\nSchreiben in der Gro\xc3\x9fstadt \nEine ganz besondere Stadtf\xc3\xbchrung erleben",
        'url' => null,
        'created_at' => '2021-07-02 06:36:16',
        'updated_at' => '2021-07-02 06:36:16',
        'deleted_at' => null,
    ],
    [
        'id' => 11,
        'name' => 'Frauenwochenende',
        'address' => 'Erzgrube bei Tamara',
        'description' => 'Alles was Frauen gerne tun!',
        'url' => null,
        'created_at' => '2021-07-02 06:50:15',
        'updated_at' => '2021-07-02 06:50:15',
        'deleted_at' => null,
    ],
];
