<?php

return [
    [
        'id' => 1,
        'method' => 'get',
        'name' => 'welcome',
        'uri' => '/',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Controller',
        'routable_id' => 6,
        'meta' => '{"controller_action": null}',
        'published' => 1,
        'created_at' => '2020-05-15 03:20:33',
        'updated_at' => '2022-05-19 01:16:03',
        'deleted_at' => null,
    ],
    [
        'id' => 2,
        'method' => 'get',
        'name' => 'events',
        'uri' => 'seminare',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Controller',
        'routable_id' => 4,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-15 03:23:40',
        'updated_at' => '2022-05-13 22:26:18',
        'deleted_at' => null,
    ],
    [
        'id' => 3,
        'method' => 'get',
        'name' => 'lectures',
        'uri' => 'vortraege',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Page',
        'routable_id' => 2,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-15 03:24:05',
        'updated_at' => '2022-05-13 23:37:36',
        'deleted_at' => null,
    ],
    [
        'id' => 4,
        'method' => 'get',
        'name' => 'consulting',
        'uri' => 'beratung',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Page',
        'routable_id' => 3,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-15 03:24:34',
        'updated_at' => '2022-05-13 23:37:42',
        'deleted_at' => null,
    ],
    [
        'id' => 5,
        'method' => 'get',
        'name' => 'learning',
        'uri' => 'lerntraining',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Page',
        'routable_id' => 4,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-15 03:25:03',
        'updated_at' => '2022-05-13 23:37:49',
        'deleted_at' => null,
    ],
    [
        'id' => 6,
        'method' => 'get',
        'name' => 'portrait',
        'uri' => 'portrait',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Page',
        'routable_id' => 5,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-15 03:25:24',
        'updated_at' => '2022-05-13 23:37:56',
        'deleted_at' => null,
    ],
    [
        'id' => 7,
        'method' => 'get',
        'name' => 'blog',
        'uri' => 'blog/{slug?}',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Controller',
        'routable_id' => 1,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-15 03:25:36',
        'updated_at' => '2022-05-13 22:26:31',
        'deleted_at' => null,
    ],
    [
        'id' => 8,
        'method' => 'get',
        'name' => 'books',
        'uri' => 'buchtipps',
        'middlewares' => '["web", "auth"]',
        'routable_type' => 'App\\Models\\Controller',
        'routable_id' => 2,
        'meta' => null,
        'published' => 0,
        'created_at' => '2020-05-15 03:25:55',
        'updated_at' => '2022-05-13 22:26:40',
        'deleted_at' => null,
    ],
    [
        'id' => 9,
        'method' => 'get',
        'name' => 'contact',
        'uri' => 'kontakt',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Page',
        'routable_id' => 6,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-15 03:26:40',
        'updated_at' => '2022-05-13 23:38:08',
        'deleted_at' => null,
    ],
    [
        'id' => 10,
        'method' => 'get',
        'name' => 'imprint',
        'uri' => 'impressum',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Page',
        'routable_id' => 7,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-20 21:38:09',
        'updated_at' => '2022-05-13 23:38:25',
        'deleted_at' => null,
    ],
    [
        'id' => 11,
        'method' => 'get',
        'name' => 'privacy-policy',
        'uri' => 'datenschutzerklaerung',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Page',
        'routable_id' => 8,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-20 21:38:48',
        'updated_at' => '2022-05-13 23:38:14',
        'deleted_at' => null,
    ],
    [
        'id' => 12,
        'method' => 'get',
        'name' => 'cookie-policy',
        'uri' => 'cookie-vereinbarung',
        'middlewares' => '["web"]',
        'routable_type' => 'App\\Models\\Controller',
        'routable_id' => 3,
        'meta' => null,
        'published' => 1,
        'created_at' => '2020-05-20 21:39:12',
        'updated_at' => '2022-05-13 22:26:50',
        'deleted_at' => null,
    ],
    [
        'id' => 13,
        'method' => 'get',
        'name' => 'gallery',
        'uri' => 'galerie',
        'middlewares' => '["web", "auth"]',
        'routable_type' => 'App\\Models\\Controller',
        'routable_id' => 5,
        'meta' => null,
        'published' => 0,
        'created_at' => '2020-06-28 01:39:38',
        'updated_at' => '2022-05-13 22:26:59',
        'deleted_at' => null,
    ],
];
