<?php

return [
    'users',
    'colors',
    'contents',
    'posts',
    'static_attributes',
    'images',
    'image_coords',
    'authors',
    'quotes',

    'content_fields',
    'content_layouts',
    'content_blocks',
    'content_views',
    'content_relations',

    'routes',
    'route_contents',
    'menus',
    'menu_items',
    'permissions',
    'roles',
    'model_has_permissions',
    'model_has_roles',
    'role_has_permissions',
    'cookie_consent_providers',
    'cookie_consent_cookies',
    'tags',
    'taggables',
    'caterings',
    'locations',
    'staff_profiles',
    'event_templates',
    'events',
    'event_registrations',
];
